### ISSUE TITLE
Not generating md file

### ISSUE THREAD

**Issue by democat3457** [Krutoy242/mc-benchmark#1]
Installed on macOS 10.15.6, mc-benchmark 1.0.4, node 16.13.2, npm 8.1.2 and 8.3.1

After running the command with no arguments, the command exits without errors or prints, but it doesn't generate an md file. The same thing happens when passing arguments, and using the logs/latest.log doesn't throw an error either.

**Comment by Krutoy242** [comment]
This is somehow related to NPM working on other platforms. It couldn't find how to execute file.

Try to run program without installing. Navigate to MC and run:
```sh
> npx mc-benchamark --help
```

If help not shown, that means program still cant be found.
In this case, you can manage to find program in globally installation directory, and use it path instead of shorten.
In Windows it:
```sh
> node "C:/Users/LD/AppData/Roaming/npm/node_modules/mc-benchmark/index.js" --help
```

Im kinda new at `npm`, so probably would figure out later why its not working properly on other platforms 😅

**Comment by Krutoy242** [comment]
If this problem is still actual feel free to comment.

**Comment by democat3457** [comment]
ok so the first one didnt work, but the second one does - for reference, the node modules are located [here](https://stackoverflow.com/questions/25045946/where-should-my-npm-modules-be-installed-on-mac-os-x) on mac
